server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Infrastructure}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user}
      roles: USER
    web:
      debug:
        enabled: ${SPRING_SECURITY_WEB_DEBUG_ENABLED:false}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  datasource-users:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERS_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_USERS_PASSWORD:1904}
    url: ${SPRING_DATASOURCE_USERS_URL:jdbc:postgresql://localhost:5432/users}

  datasource-resources:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_RESOURCES_USERNAME:resources}
    password: ${SPRING_DATASOURCE_RESOURCES_PASSWORD:1904}
    url: ${SPRING_DATASOURCE_RESOURCES_URL:jdbc:postgresql://localhost:5432/resources}

  redis-users:
    host: ${SPRING_REDIS_USERS_HOST:localhost}
    port: ${SPRING_REDIS_USERS_PORT:6379}
    database: ${SPRING_REDIS_USERS_DATABASE:0}
    password: ${SPRING_REDIS_USERS_PASSWORD:1904}

  flyway-resources:
    url: ${SPRING_DATASOURCE_RESOURCES_URL:jdbc:postgresql://localhost:5432/resources}
    user: ${SPRING_DATASOURCE_RESOURCES_USERNAME:resources}
    password: ${SPRING_DATASOURCE_RESOURCES_PASSWORD:1904}
    locations: ${SPRING_FLYWAY_RESOURCES_LOCATIONS:classpath:migrations/resources}
    out-of-order: true
    baseline-on-migrate: true
    enabled: ${SPRING_FLYWAY_RESOURCES_ENABLED:true}

api:
  resources:
    images:
      size: ${CLOUDINARY_FILES_SIZE_LIMIT:25}
      host: ${CLOUDINARY_HOST:https://api.cloudinary.com/v1_1/dqjeb0ob2/image}
      key: ${CLOUDINARY_KEY:474919738819372}
      secret: ${CLOUDINARY_SECRET:SlJA8pvuSIgcPX1CoAagGE-qWyE}

logging:
  level:
    io.management: DEBUG
    root: INFO
