spring:
  profiles:
    active: default, native, dev
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${UDB_USERNAME}
    url: ${UDB_URL}
    password: ${UDB_PASSWORD}
