spring:
  profiles:
    active: default, native, dev
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${UDB_USERNAME:postgres}
    password: ${UDB_PASSWORD:1904}
    url: ${UDB_URL}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATA:2}