spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
  datasource-users:
    driver-class-name: org.postgresql.Driver
    username: ${USER_READER_DB_USERNAME:users_reader}
    password: ${USER_READER_DB_PASSWORD:1904}
    url: ${USER_READER_DB_URL:jdbc:postgresql://localhost:5432/users}
  datasource-resources:
    driver-class-name: org.postgresql.Driver
    username: ${RESOURCE_DB_USERNAME:resources}
    password: ${RESOURCE_DB_PASSWORD:1904}
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resources}
  redis-users:
    host: ${REDIS_HOST_INFRASTRUCTURE:localhost}
    port: ${REDIS_PORT_INFRASTRUCTURE:6379}
    database: ${REDIS_DATABASE_INFRASTRUCTURE:0}
    password: ${REDIS_PASSWORD_INFRASTRUCTURE:1904}

api:
  resources:
    images:
      size: 25
      host: ${CLOUDINARY_HOST:https://api.cloudinary.com/v1_1/dqjeb0ob2/image}
      key: ${CLOUDINARY_KEY:474919738819372}
      secret: ${CLOUDINARY_SECRET:SlJA8pvuSIgcPX1CoAagGE-qWyE}
logging:
  level:
    io.management: DEBUG
