spring:
  profiles:
    active: default, native, dev
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
  datasource-users:
    driver-class-name: org.postgresql.Driver
    username: ${USER_READER_DB_USERNAME:users_reader}
    password: ${USER_READER_DB_PASSWORD:1904}
    url: ${USER_READER_DB_URL}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1904}
    url: ${DB_URL}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST_INFRASTRUCTURE:localhost}
    port: ${REDIS_PORT_INFRASTRUCTURE:6379}
    database: ${REDIS_DATABASE_INFRASTRUCTURE:0}
    password: ${REDIS_PASSWORD_INFRASTRUCTURE:1904}