CREATE TABLE IF NOT EXISTS images(
    public_id          VARCHAR PRIMARY KEY,
    asset_id           VARCHAR,
    version            BIGINT,
    version_id         VARCHAR,
    signature          VARCHAR,
    width              INTEGER,
    height             INTEGER,
    format             VARCHAR,
    resource_type      VARCHAR,
    created_at         VARCHAR,
    tags               VARCHAR,
    bytes              BIGINT,
    type               VARCHAR,
    etag               VARCHAR,
    placeholder        BOOLEAN,
    url                VARCHAR,
    secure_url         VARCHAR,
    folder             VARCHAR,
    access_mode        VARCHAR,
    overwritten        BOOLEAN,
    original_filename  VARCHAR,
    original_extension VARCHAR
)